### ISSUE TITLE
KeyError: 'uk' when running the sample code

### ISSUE THREAD

**Issue by trumad** [pbexe/tesco#1]
Hey! Thanks for the work on this. I copy/pasted your test code into a .py file and ran it, but saw only the following error:

`python test.py 
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    results = t.grocery_search("cake", offset=0, limit=100)
  File "/Users/tmackarel/.pyenv/versions/3.7.3/lib/python3.7/site-packages/tesco/main.py", line 43, in grocery_search
    return r.json()["uk"]["ghs"]["products"]["results"]
KeyError: 'uk'
`

Are you still actively developing this? Or should I fork and try to fix it? My Python is basic at best...

**Comment by pbexe** [comment]
Hi,
I haven't done any work on this in a while but it seems to still be working. When you copy/pasted the example code, did you replace the placeholder with your API key on the `t = Tesco("API KEY")` line? This seems to give the same error.

**Comment by trumad** [comment]
Ha, silly me. Didn't spot that line. I thought maybe you were hitting the frontend api. I'll give this a go, thanks!

**Comment by trumad** [comment]
Ah. Tesco have suspended their API for now: https://devportal.tescolabs.com/products/56c73300d73fa303ed060001

"API access is suspended

API access has been suspended to focus efforts on maintaining critical systems."

This can probably be closed, from your perspective. I'll check out your python module when the API is working again. Thanks!

**Comment by pbexe** [comment]
That's a shame. If you really need a key you can send me an email.
